{
  "hash": "3310f56375abde4c46d1c3b119a36bba",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Comparing the unit dose reported in the SCMD to the unit dose calculated using the dm+d\"\ndate: 2026-09-01\ncategories: [draft]\ndescription: \"A comparison of the unit dose quantity newly reported in the provisional Secondary Care Medicines Data (SCMD) extract with the unit dose calculated from the dm+d in  the OpenPrescribing Hospitals data.\"\njupyter: python3\nexecute:\n  echo: false\n---\n\n\n\n## Background\n\nThe following notice was added to the [provisional Secondary Care Medicines Data (SCMD)](https://opendata.nhsbsa.net/dataset/secondary-care-medicines-data-indicative-price) on the NHS Business Services Authority (NHSBSA) Open Data Portal on 25/08/2026:\n\n> Changes have now been introduced to the Secondary Care Medicines Dataset (SCMD) with the\\\n> June 2026 Provisional data release.\n>\n> The changes include updates to existing column names and the addition of new columns relating to Virtual Medicinal Product (VMP) unit of measure and quantity.\n>\n> Column name changes\n>\n> UNIT_OF_MEASURE_NAME → VMP_UDFS_UNIT_OF_MEASURE_NAME\n>\n> UNIT_OF_MEASURE_IDENTIFIER → VMP_UDFS_UNIT_OF_MEASURE_IDENTIFIER\n>\n> TOTAL_QUANITY_IN_VMP_UNIT → TOTAL_QUANTITY_IN_VMP_UDFS_UNIT_OF_MEASURE New columns\n>\n> VMP_UNIT_DOSE_UNIT_OF_MEASURE_NAME – Virtual Medicinal Product (VMP) Unit Dose Unit of Measure name\n>\n> TOTAL_QUANTITY_IN_VMP_UNIT_DOSE_UNIT_OF_MEASURE – Total quantity in Virtual Medicinal \\>Product (VMP) Unit Dose Unit of Measure SNOMED code and unit of measure identifier fields are also now provided as string data types.\n>\n> The Finalised SCMD dataset is published annually and will next be updated in July 2027,\\\n> covering data for April 2026 to March 2027. The changes introduced to the Provisional dataset will therefore be reflected in the Finalised dataset as part of this annual update.\n\nThe unit dose quantity is a quantity that we have previously had to calculate by linking the SCMD to the dm+d, identifying the UDFS value and unit of measure in the dm+d, and converting the quantity reported in the SCMD to the unit dose quantity. We have described how we do this in our blog post, [Calculating unit dose quantity in the Secondary Care Medicines Data](https://www.bennett.ox.ac.uk/blog/2025/06/calculating-unit-dose-quantity-in-the-secondary-care-medicines-data/).\n\nInclusion of the unit dose quantity in the raw SCMD will allow us to simplify the processing required for use of the data by OpenPrescribing Hospitals. But before we replace the current unit dose quantity calculation, we need to check that the unit doses now reported in the SCMD agrees with the unit doses we have determined using the extra information available through the dm+d.\n\nBelow, we describe this comparison.\n\n## Methods\n\nThe analysis uses two data sources:\n\n1.  The June 2026 provisional SCMD extract (the only data extract with the additional columns at the time of analysis).\n2.  The product information used by OpenPrescribing Hospitals, taken from the dm+d.\n\nTo make the comparison, we first identify all of the unique Virtual Medicinal Products (VMPs) that are reported in the June 2026 provisional SCMD extract. For these products, we identify the UDFS unit of measure from the renamed `VMP_UDFS_UNIT_OF_MEASURE_NAME` column and the unit dose unit of measure from the `VMP_UNIT_DOSE_UNIT_OF_MEASURE_NAME` column.\n\nFor all of the identified VMPs, we then find the UDFS unit of measure, the UDFS value, and the unit dose unit of measure that are currently used in OpenPrescribing Hospitals.\n\nWe compare the UDFS unit of measure and the unit dose unit of measure in the provisional extract with the equivalent fields in the OpenPrescribing Hospitals data.\n\nWe count the number of VMPs for which these values agree and for which they do not. Where they do not, we split this count out into:\n\n- **values different** - both sources have a UDFS unit of measure, and the values are different\n- **UDFS unit missing in OpenPrescribing Hospitals** - the VMP has a UDFS unit of measure in the provisional extract, but not in OpenPrescribing Hospitals\n- **UDFS unit missing in the provisional extract** - the VMP has a UDFS unit of measure in the OpenPrescribing Hospitals data, but not in the provisional extract\n\nWhere the UDFS units of measure are different, we also report whether the UDFS values are different.\n\nWe also identify any VMPs which are reported in the provisional extract, but not in the OpenPrescribing Hospitals data.\n\nWe then compare unit dose form size (UDFS). The provisional extract does not include a UDFS value column, so we have to back-calculate it from the two reported quantity fields. For each organisation row we calculate:\n\n```         \nQuantity in the UDFS unit of measure / quantity in the unit dose unit of measure\n```\n\n(We've described the differences between unit dose and unit dose form in our blog post, [Getting more from the Secondary Care Medicines Data using the Dictionary of Medicines and Devices](https://www.bennett.ox.ac.uk/blog/2025/03/getting-more-from-the-secondary-care-medicines-data-using-the-dictionary-of-medicines-and-devices/#virtual-medicinal-product-vmp).)\n\nWe first check that this value is the same for all organisation rows of a VMP. A relative difference of 0.1% or less between the minimum and maximum counts as the same.\n\nWe then compare that UDFS with UDFS in the OpenPrescribing Hospitals data. We restrict this comparison to VMPs where the UDFS unit of measure already agrees.\n\nWe also compare the unit dose unit of measure in the new `VMP_UNIT_DOSE_UNIT_OF_MEASURE_NAME` column with `unit_dose_uom` in OpenPrescribing Hospitals. We use the same agreement categories as for the UDFS unit of measure.\n\n## Findings\n\n::: {#3cc9a9bb .cell execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nThe provisional extract has **8,366** unique VMP codes. Of these, the UDFS units of measure agree for **5,891 (70.4%)**. **2,453 (29.3%)** do not agree. **22 (0.3%)** are in the provisional extract, but not in the data used by OpenPrescribing Hospitals (there will be newly introduced VMPs only reported in the June 2026 provisional extract).\n:::\n:::\n\n\n::: {#73a8b6e8 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Status | VMPs | Share |\n| --- | --- | --- |\n| Agree | 5,891 | 70.4% |\n| values different | 0 | 0.0% |\n| UDFS unit missing in OpenPrescribing Hospitals | 2,453 | 29.3% |\n| UDFS unit missing in the provisional extract | 0 | 0.0% |\n| VMP not in OpenPrescribing Hospitals | 22 | 0.3% |\n:::\n:::\n\n\n::: {#14ee89d5 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nWhere both sources have a UDFS unit of measure (5,891 VMPs), **5,891 agree (100.0%)** and **0 have differing UDFS units of measure (0.0%)**.\n:::\n:::\n\n\n### Products with differing UDFS units of measure\n\n::: {#f8eb3ded .cell execution_count=5}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nNo VMPs have different UDFS units of measure in both sources.\n:::\n:::\n\n\n::: {#c6c4735d .cell execution_count=6}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nNo rows.\n:::\n:::\n\n\n::: {#91b04605 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nNo VMPs have different UDFS units of measure in both sources, so there are no UDFS value differences to report for this group.\n:::\n:::\n\n\n### Products with UDFS unit missing in OpenPrescribing Hospitals\n\n::: {#e5c77dfc .cell execution_count=8}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n**2,453** VMPs have a UDFS unit of measure in the provisional extract, but not in OpenPrescribing Hospitals.\n:::\n:::\n\n\nThe UDFS units of measure for these products are shown below.\n\n::: {#aaff31a9 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Provisional UDFS unit of measure | VMPs |\n| --- | --- |\n| ML | 1,213 |\n| GRAM | 528 |\n| DRESSING | 279 |\n| DEVICE | 95 |\n| SACHET | 48 |\n| BOTTLE | 27 |\n| UNIT DOSE | 25 |\n| TABLET | 23 |\n| LITRE | 22 |\n| Other (29 values) | 193 |\n:::\n:::\n\n\nThe dose form indicators for these VMPs is shown below.\n\n::: {#550df88d .cell execution_count=10}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| `df_ind` | VMPs | Share |\n| --- | --- | --- |\n| Continuous | 1,318 | 53.7% |\n| Not applicable | 1,135 | 46.3% |\n| Discrete | 0 | 0.0% |\n:::\n:::\n\n\nAll of the products with a UDFS unit reported in the provisional extract but not in OpenPrescribing Hospitals have a `Continuous` or `Not applicable` dose form indicator. In the processing pipeline for OpenPrescribing Hospitals, these products are excluded from the unit dose quantity calculations as unit doses are not applicable to these products.\n\n::: {#0e8bc190 .cell execution_count=11}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nFor **2,453 of 2,453** of these VMPs, the provisional UDFS unit of measure is the same as the provisional unit dose unit of measure. The implied UDFS is 1 on every organisation row for **2,453 of 2,453** VMPs. This is consistent with treating the UDFS units as unit dose units for these products.\n:::\n:::\n\n\nThe UDFS units of measure for these cases are shown below.\n\n::: {#a637954e .cell execution_count=12}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| `df_ind` | Provisional UDFS unit of measure | VMPs |\n| --- | --- | --- |\n| Continuous | ML | 898 |\n| Continuous | GRAM | 390 |\n| Not applicable | ML | 315 |\n| Not applicable | DRESSING | 269 |\n| Not applicable | GRAM | 138 |\n| Not applicable | DEVICE | 95 |\n| Not applicable | SACHET | 46 |\n| Not applicable | BOTTLE | 24 |\n| Not applicable | TABLET | 23 |\n| Not applicable | UNIT DOSE | 22 |\n:::\n:::\n\n\n### Products with UDFS unit missing in the provisional extract\n\n::: {#72b230e8 .cell execution_count=13}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n**0** VMPs have a UDFS unit of measure in OpenPrescribing Hospitals, but not in the provisional extract.\n:::\n:::\n\n\n::: {#a3c60e0f .cell execution_count=14}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nNo rows.\n:::\n:::\n\n\n### VMPs not in OpenPrescribing Hospitals\n\n::: {#2f3a1fa8 .cell execution_count=15}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n**22** VMPs are in the provisional extract, but not in the OpenPrescribing Hospitals data.\n:::\n:::\n\n\n::: {#db8bb7e3 .cell execution_count=16}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Product | Provisional UDFS unit of measure |\n| --- | --- |\n| Apixaban 1mg/ml oral suspension sugar free | ML |\n| Bisoprolol 500micrograms/ml oral solution sugar free | ML |\n| Chlorhexidine gluconate 0.1% eye drops | ML |\n| Compression hosiery class II kneecap flatbed knit made to measure | STOCKING |\n| Doxepin 50mg/5ml oral solution | ML |\n| Ethanol 95% solution for infusion 20ml ampoules | ML |\n| Fluorouracil 1% eye drops preservative free | ML |\n| Generic AC-F 213 liquid acid concentrate for haemodialysis 4.7litre containers | UNIT |\n| Generic Aspergillus fumigatus 10,000BU/ml solution for skin prick test | ML |\n| Generic Comirnaty KP.2 adults and adolescents from 12 years COVID-19 mRNA Vaccine 30micrograms/0.3ml dose dispersion for injection pre-filled syringes | ML |\n| Generic Silonda sensitive skin care lotion | ML |\n| Generic Skinsan 2% antimicrobial wash | ML |\n| Glycopyrronium 8mg/g cream (2.2mg per actuation) | GRAM |\n| Hyoscine butylbromide 5mg/5ml oral solution | ML |\n| Knee pressure offloading device | DEVICE |\n| Methylphenidate 10mg/5ml oral solution | ML |\n| Methylphenidate 40mg modified-release chewable tablets sugar free | TABLET |\n| Nusinersen 50mg/5ml solution for injection vials | ML |\n| Phenobarbital 50mg/5ml oral suspension sugar free | ML |\n| Serplulimab 100mg/10ml solution for infusion vials | ML |\n| Sodium hyaluronate 0.1% / Ectoine 2% eye drops preservative free | ML |\n| Terlipressin 1mg/8.5ml solution for injection vials | ML |\n:::\n:::\n\n\n### Unit dose form size (UDFS)\n\n::: {#f6a6a24c .cell execution_count=17}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nFor **8,366 of 8,366** VMPs (100.0%), the implied UDFS is the same on every organisation row. \n:::\n:::\n\n\n::: {#22b519fe .cell execution_count=18}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nNo VMPs have a different implied UDFS across organisation rows.\n:::\n:::\n\n\n::: {#a0ece98c .cell execution_count=19}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nAmong the **5,891** VMPs where the UDFS unit of measure agrees, UDFS agrees for **5,663**. **228** have different UDFS values.\n:::\n:::\n\n\n::: {#4746f8ed .cell execution_count=20}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nThe VMPs with the same UDFS unit of measure and a different UDFS are shown below.\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Product | UDFS unit of measure | Provisional UDFS | OpenPrescribing Hospitals UDFS |\n| --- | --- | --- | --- |\n| Aciclovir 200mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Aciclovir 400mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Activated charcoal 81.3% granules for gastroenteral or oral suspension sugar free | GRAM | 1 | 50 |\n| Alginate raft-forming oral suspension sugar free | ML | 1 | 5 |\n| Alimemazine 30mg/5ml oral solution | ML | 1 | 5 |\n| Alimemazine 30mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Alimemazine 7.5mg/5ml oral solution | ML | 1 | 5 |\n| Alimemazine 7.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Alpha tocopheryl acetate 500mg/5ml oral suspension | ML | 1 | 5 |\n| Amantadine 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amiloride 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amitriptyline 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amitriptyline 25mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amitriptyline 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amlodipine 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amlodipine 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Amlodipine 5mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Amoxicillin 125mg/5ml oral suspension | ML | 1 | 5 |\n| Amoxicillin 125mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Amoxicillin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Amoxicillin 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Amoxicillin 500mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Atenolol 25mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Atovaquone 750mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Azithromycin 200mg/5ml oral suspension | ML | 1 | 5 |\n| Baclofen 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Bumetanide 1mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Captopril 25mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Captopril 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Carbamazepine 100mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Carbocisteine 250mg/5ml oral solution | ML | 1 | 5 |\n| Carbocisteine 250mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Carbocisteine 750mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Cefaclor 125mg/5ml oral suspension | ML | 1 | 5 |\n| Cefaclor 250mg/5ml oral suspension | ML | 1 | 5 |\n| Cefalexin 125mg/5ml oral suspension | ML | 1 | 5 |\n| Cefalexin 125mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Cefalexin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Cefalexin 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Chloral hydrate 143.3mg/5ml oral solution BP | ML | 1 | 5 |\n| Chloral hydrate 500mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Chlorothiazide 250mg/5ml oral suspension | ML | 1 | 5 |\n| Chlorphenamine 2mg/5ml oral solution | ML | 1 | 5 |\n| Chlorphenamine 2mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Chlorpromazine 25mg/5ml oral solution | ML | 1 | 5 |\n| Chlorpromazine 25mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Cimetidine 200mg/5ml oral solution | ML | 1 | 5 |\n| Cimetidine 200mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Ciprofloxacin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Clarithromycin 125mg/5ml oral suspension | ML | 1 | 5 |\n| Clarithromycin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Clobazam 10mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Clobazam 5mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-amoxiclav 125mg/31mg/5ml oral suspension | ML | 1 | 5 |\n| Co-amoxiclav 125mg/31mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-amoxiclav 250mg/62mg/5ml oral suspension | ML | 1 | 5 |\n| Co-amoxiclav 250mg/62mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-amoxiclav 400mg/57mg/5ml oral suspension | ML | 1 | 5 |\n| Co-amoxiclav 400mg/57mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-magaldrox 195mg/220mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-trimoxazole 40mg/200mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Co-trimoxazole 80mg/400mg/5ml oral suspension | ML | 1 | 5 |\n| Codeine 15mg/5ml linctus | ML | 1 | 5 |\n| Codeine 15mg/5ml linctus sugar free | ML | 1 | 5 |\n| Desloratadine 2.5mg/5ml oral solution | ML | 1 | 5 |\n| Desloratadine 2.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Dexamethasone 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Dexamethasone 2mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Dextromethorphan 7.5mg/5ml / Menthol 2.5mg/5ml oral solution | ML | 1 | 5 |\n| Dextromethorphan 7.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Diazepam 2mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Diazepam 2mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Dicycloverine 10mg/5ml oral solution | ML | 1 | 5 |\n| Dipyridamole 50mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Disodium hydrogen phosphate dodecahydrate 895mg/5ml oral solution | ML | 1 | 5 |\n| Docusate 100mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Docusate 12.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Docusate 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Donepezil 1mg/ml oral solution sugar free | ML | 1 | 5 |\n| Enalapril 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Erythromycin ethyl succinate 125mg/5ml oral suspension | ML | 1 | 5 |\n| Erythromycin ethyl succinate 125mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Erythromycin ethyl succinate 250mg/5ml oral suspension | ML | 1 | 5 |\n| Erythromycin ethyl succinate 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Erythromycin ethyl succinate 500mg/5ml oral suspension | ML | 1 | 5 |\n| Erythromycin ethyl succinate 500mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Estradiol 0.06% transdermal gel (750microgram per actuation) | GRAM | 1 | 1.25 |\n| Ethosuximide 250mg/5ml oral solution | ML | 1 | 5 |\n| Ethosuximide 250mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Ferrous fumarate 140mg/5ml oral solution | ML | 1 | 5 |\n| Ferrous fumarate 140mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Flecainide 25mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Flucloxacillin 125mg/5ml oral solution | ML | 1 | 5 |\n| Flucloxacillin 125mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Flucloxacillin 125mg/5ml oral suspension | ML | 1 | 5 |\n| Flucloxacillin 250mg/5ml oral solution | ML | 1 | 5 |\n| Flucloxacillin 250mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Flucloxacillin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Fluconazole 200mg/5ml oral suspension | ML | 1 | 5 |\n| Fluconazole 50mg/5ml oral suspension | ML | 1 | 5 |\n| Fluoxetine 20mg/5ml oral solution | ML | 1 | 5 |\n| Fluoxetine 20mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Folic acid 2.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Folic acid 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Fosfomycin 250mg/5ml oral suspension | ML | 1 | 5 |\n| Furosemide 20mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Furosemide 40mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Fusidic acid 250mg/5ml oral suspension | ML | 1 | 5 |\n| Generic Benylin Dry Coughs Night syrup | ML | 1 | 5 |\n| Generic Gaviscon Double Action Liquid sugar free | ML | 1 | 5 |\n| Generic Glycerin, Honey and Lemon linctus | ML | 1 | 5 |\n| Generic LiQ-10 50mg/5ml syrup | ML | 1 | 5 |\n| Generic Minadex tonic | ML | 1 | 5 |\n| Generic Neo Baby Gripe mixture | ML | 1 | 5 |\n| Generic Vigranon-B syrup sugar free | ML | 1 | 5 |\n| Guaifenesin 100mg/5ml / Levomenthol 1.1mg/5ml oral solution | ML | 1 | 5 |\n| Guaifenesin 100mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Hydrocortisone 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Hydrocortisone 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Hydroxyzine 10mg/5ml oral solution | ML | 1 | 5 |\n| Ibuprofen 100mg/5ml / Pseudoephedrine 15mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Ibuprofen 100mg/5ml oral suspension | ML | 1 | 5 |\n| Ibuprofen 100mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Ibuprofen 200mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Indocyanine green 25mg/10ml solution for injection ampoules | ML | 1 | 10 |\n| Indometacin 25mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Itraconazole 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Ketotifen 1mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Lactulose 3.1-3.7g/5ml oral solution | ML | 1 | 5 |\n| Lamivudine 50mg/5ml oral solution | ML | 1 | 5 |\n| Levothyroxine sodium 100micrograms/5ml oral solution sugar free | ML | 1 | 5 |\n| Levothyroxine sodium 125micrograms/5ml oral solution sugar free | ML | 1 | 5 |\n| Levothyroxine sodium 25micrograms/5ml oral solution sugar free | ML | 1 | 5 |\n| Levothyroxine sodium 50micrograms/5ml oral solution sugar free | ML | 1 | 5 |\n| Linezolid 100mg/5ml oral suspension | ML | 1 | 5 |\n| Lithium citrate 1.018g/5ml oral solution | ML | 1 | 5 |\n| Lithium citrate 509mg/5ml oral solution | ML | 1 | 5 |\n| Lithium citrate 520mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Lofepramine 70mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Loperamide 1mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Loperamide 5mg/5ml oral suspension | ML | 1 | 5 |\n| Lopinavir 400mg/5ml / Ritonavir 100mg/5ml oral solution | ML | 1 | 5 |\n| Loratadine 5mg/5ml oral solution | ML | 1 | 5 |\n| Loratadine 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Magnesium hydroxide 7.45-8.35% oral suspension BP | ML | 1 | 5 |\n| Magnesium hydroxide 8% oral suspension | ML | 1 | 5 |\n| Mannitol 125mg/5ml oral solution | ML | 1 | 5 |\n| Mebendazole 100mg/5ml oral suspension | ML | 1 | 5 |\n| Mebeverine 50mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Meglumine amidotrizoate 3.3g/5ml / Sodium amidotrizoate 500mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Metformin 500mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Metronidazole 200mg/5ml oral suspension | ML | 1 | 5 |\n| Morphine sulfate 10mg/5ml oral solution | ML | 1 | 5 |\n| Mycophenolate mofetil 1g/5ml oral suspension sugar free | ML | 1 | 5 |\n| Naproxen 250mg/5ml oral suspension | ML | 1 | 5 |\n| Nevirapine 50mg/5ml oral suspension | ML | 1 | 5 |\n| Nimodipine 60mg/5ml oral suspension | ML | 1 | 5 |\n| Nitrazepam 2.5mg/5ml oral suspension | ML | 1 | 5 |\n| Nitrazepam 2.5mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Nitrofurantoin 25mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Omeprazole 10mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Omeprazole 20mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Ondansetron 4mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Orphenadrine 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Oxybutynin 2.5mg/5ml oral solution | ML | 1 | 5 |\n| Oxybutynin 2.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Oxybutynin 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Oxycodone 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Paracetamol 120mg/5ml oral solution paediatric | ML | 1 | 5 |\n| Paracetamol 120mg/5ml oral solution paediatric sugar free | ML | 1 | 5 |\n| Paracetamol 120mg/5ml oral suspension paediatric | ML | 1 | 5 |\n| Paracetamol 120mg/5ml oral suspension paediatric sugar free | ML | 1 | 5 |\n| Paracetamol 250mg/5ml oral suspension | ML | 1 | 5 |\n| Paracetamol 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Paracetamol 500mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Phenoxymethylpenicillin 125mg/5ml oral solution | ML | 1 | 5 |\n| Phenoxymethylpenicillin 125mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Phenoxymethylpenicillin 250mg/5ml oral solution | ML | 1 | 5 |\n| Phenoxymethylpenicillin 250mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Phenytoin 30mg/5ml oral suspension | ML | 1 | 5 |\n| Pizotifen 250micrograms/5ml oral solution sugar free | ML | 1 | 5 |\n| Potassium chloride 375mg/5ml (potassium 5mmol/5ml) oral solution sugar free | ML | 1 | 5 |\n| Procyclidine 2.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Procyclidine 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Promazine 25mg/5ml oral solution | ML | 1 | 5 |\n| Promazine 50mg/5ml oral solution | ML | 1 | 5 |\n| Promethazine 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Propranolol 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Propranolol 40mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Propranolol 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Propranolol 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Pyridostigmine bromide 60mg/5ml oral solution | ML | 1 | 5 |\n| Ramipril 2.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Rifaximin 100mg/5ml oral suspension | ML | 1 | 5 |\n| Riluzole 25mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Salbutamol 2mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Senna 7.5mg/5ml oral solution | ML | 1 | 5 |\n| Sennosides 7.5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Sertraline 50mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Simple linctus | ML | 1 | 5 |\n| Simple linctus paediatric | ML | 1 | 5 |\n| Simple linctus paediatric sugar free | ML | 1 | 5 |\n| Simple linctus sugar free | ML | 1 | 5 |\n| Sodium alginate 500mg/5ml / Potassium bicarbonate 100mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Sodium feredetate (iron 27.5mg/5ml) oral solution sugar free | ML | 1 | 5 |\n| Sodium picosulfate 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Sodium valproate 200mg/5ml oral solution | ML | 1 | 5 |\n| Sodium valproate 200mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Solifenacin 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Sucralfate 1g/5ml oral suspension sugar free | ML | 1 | 5 |\n| Sulfasalazine 250mg/5ml oral suspension | ML | 1 | 5 |\n| Sulfasalazine 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Sulpiride 200mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Tamoxifen 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Temazepam 10mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Testosterone 16.2mg/g transdermal gel (20.25mg per actuation) | GRAM | 1 | 1.25 |\n| Testosterone 2% transdermal gel (10mg per actuation) | GRAM | 1 | 0.5 |\n| Testosterone 20mg/g transdermal gel (23mg per actuation) refill | GRAM | 1 | 1.15 |\n| Testosterone 20mg/g transdermal gel (23mg per actuation) with applicator | GRAM | 1 | 1.15 |\n| Theophylline 60mg/5ml oral solution | ML | 1 | 5 |\n| Tobramycin 200mg/5ml oral solution | ML | 1 | 5 |\n| Trazodone 50mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Trifluoperazine 1mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Trifluoperazine 5mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Trihexyphenidyl 5mg/5ml oral solution | ML | 1 | 5 |\n| Ursodeoxycholic acid 250mg/5ml oral suspension sugar free | ML | 1 | 5 |\n| Verapamil 40mg/5ml oral solution sugar free | ML | 1 | 5 |\n| Voriconazole 200mg/5ml oral suspension | ML | 1 | 5 |\n:::\n:::\n\n\n### Unit dose unit of measure\n\n::: {#5f10a750 .cell execution_count=21}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nThe unit dose units of measure agree for **5,663 (67.7%)**. **2,681 (32.0%)** do not agree. **22 (0.3%)** are in the provisional extract, but not in the data used by OpenPrescribing Hospitals.\n:::\n:::\n\n\n::: {#c692ef59 .cell execution_count=22}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Status | VMPs | Share |\n| --- | --- | --- |\n| Agree | 5,663 | 67.7% |\n| values different | 228 | 2.7% |\n| Unit dose unit missing in OpenPrescribing Hospitals | 2,453 | 29.3% |\n| Unit dose unit missing in the provisional extract | 0 | 0.0% |\n| VMP not in OpenPrescribing Hospitals | 22 | 0.3% |\n:::\n:::\n\n\n::: {#84850237 .cell execution_count=23}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nWhere both sources have a unit dose unit of measure (5,891 VMPs), **5,663 agree (96.1%)** and **228 have differing unit dose units of measure (3.9%)**.\n:::\n:::\n\n\n::: {#60b43841 .cell execution_count=24}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n**228** VMPs have a unit dose unit of measure in both sources, and the values are different. The most common pair is ML in the provisional extract and spoonful in OpenPrescribing Hospitals (220 VMPs).\n:::\n:::\n\n\n::: {#bea6e38c .cell execution_count=25}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n| Provisional unit dose unit of measure | OpenPrescribing Hospitals unit dose unit of measure | VMPs |\n| --- | --- | --- |\n| ML | spoonful | 220 |\n| GRAM | actuation | 5 |\n| GRAM | bottle | 1 |\n| ML | ampoule | 1 |\n| ML | vial | 1 |\n:::\n:::\n\n\n::: {#180ea995 .cell execution_count=26}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n**2,453** VMPs have a unit dose unit of measure in the provisional extract, but not in OpenPrescribing Hospitals. **0** VMPs have a unit dose unit of measure in OpenPrescribing Hospitals, but not in the provisional extract.\n:::\n:::\n\n\n\n\n## Conclusions\n\n::: {#a585ccb5 .cell execution_count=28}\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nFor all **5,891** VMPs where both sources have a UDFS unit of measure, the units agree for **5,891**. OpenPrescribing Hospitals has no UDFS unit for **2,453** VMPs. All of these products have a `Continuous` or `Not applicable` dose form indicator, for which unit doses are not applicable. For all of these products, the provisional UDFS unit is the same as the provisional unit dose unit and the implied UDFS is 1 on every organisation row. This is consistent with treating the UDFS units as unit dose units for these products.\n:::\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\nFor the **5,891** VMPs with matching UDFS units, the implied UDFS value agrees for **5,663**. **228** have different UDFS values. The most common pair is an implied UDFS of 1 ML in the provisional extract and a UDFS of 5 ML in OpenPrescribing Hospitals (221 VMPs). These differences need further investigation.\n:::\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}